hallo_verden_queue_notifications:
    messenger_transport_has_stopped_event:
        async:
            event_intervals: [3600]
            max_worker_running_interval: 5 minutes
    messenger_transport_has_messages_event:
        failed:
            event_intervals: [3600]
            max_messages: 0
